INSERT INTO `recap`.`BULK_CUSTOMER_CODE_T` (`BULK_CUSTOMER_CODE_ID`,`CUSTOMER_CODE`,`DESCRIPTION`,`OWNING_INST_ID`) VALUES(1,'B1','CUL Bulk Request',2);
INSERT INTO `recap`.`BULK_CUSTOMER_CODE_T` (`BULK_CUSTOMER_CODE_ID`,`CUSTOMER_CODE`,`DESCRIPTION`,`OWNING_INST_ID`) VALUES(2,'B2','NYPL Bulk request',3);
INSERT INTO `recap`.`BULK_CUSTOMER_CODE_T` (`BULK_CUSTOMER_CODE_ID`,`CUSTOMER_CODE`,`DESCRIPTION`,`OWNING_INST_ID`) VALUES(3,'B3','PUL Bulk request',1);
INSERT INTO `recap`.`BULK_CUSTOMER_CODE_T` (`BULK_CUSTOMER_CODE_ID`,`CUSTOMER_CODE`,`DESCRIPTION`,`OWNING_INST_ID`) VALUES(4,'G1','Columbia\'s Google code',2);
INSERT INTO `recap`.`BULK_CUSTOMER_CODE_T` (`BULK_CUSTOMER_CODE_ID`,`CUSTOMER_CODE`,`DESCRIPTION`,`OWNING_INST_ID`) VALUES(5,'GO','NYPL\'s Google code',3);
INSERT INTO `recap`.`BULK_CUSTOMER_CODE_T` (`BULK_CUSTOMER_CODE_ID`,`CUSTOMER_CODE`,`DESCRIPTION`,`OWNING_INST_ID`) VALUES(6,'G2','Princeton\'s Google Code',1);